Feature/back get one
DMarjar/project-dudu pull request #17
Opened 2024-06-20 16:24 UTC by DaddyDany

2024-06-20 16:39 UTC, DMarjar requested changes
El archivo de get all missions tiene conflictos de merge y se quedó lo de HEAD

2024-06-20 16:39 UTC, DMarjar commented on modules/missions/get_all_missions/app.py
> +<<<<<<< HEAD
Conflicto de git sin arreglar

2024-06-24 01:05 UTC, DaddyDany commented on modules/missions/get_all_missions/app.py
> +<<<<<<< HEAD
ya

2024-06-24 01:05 UTC, DaddyDany reviewed
Ya quedo

2024-06-24 01:06 UTC, DaddyDany reviewed
Alv como funciona esto

2024-06-24 03:43 UTC, DaddyDany reviewed
test finished

2024-06-24 04:15 UTC, DMarjar requested changes

2024-06-24 04:15 UTC, DMarjar commented on modules/missions/get_one_mission/app.py
> +from modules.missions.get_one_mission.common.db_connection import get_db_connection
esta conexion es desde raiz, no funcionará en AWS. Tiene que ser relativa desde este archivo para que jale

2024-06-28 20:23 UTC, DMarjar approved these changes

2024-07-01 04:02 UTC, merged