Feature/back insert mission
DMarjar/project-dudu pull request #20
Opened 2024-06-28 16:04 UTC by Tlacuano

2024-06-28 16:11 UTC, DMarjar requested changes

2024-06-28 16:11 UTC, DMarjar commented on .idea/aws.xml
deja de subir este archivo chamaco

2024-06-28 16:11 UTC, DMarjar commented on .idea/project-dudu.iml
deja de subir este archivo chamaco

2024-06-28 16:15 UTC, Tlacuano commented on .idea/aws.xml
y como lo elimino?

2024-06-28 16:21 UTC, DMarjar requested changes

2024-06-28 16:21 UTC, DMarjar commented on .gitattributes
> +.idea/project-dude.iml
dice "project-dude", no "project-dudu"

2024-06-28 16:21 UTC, DMarjar commented on .gitattributes
> +idea/project-dude.iml
dice "project-dude", no "project-dudu"

2024-06-29 03:47 UTC, Tlacuano commented on .gitattributes
> +.idea/project-dude.iml
xd

2024-07-01 02:14 UTC, DaddyDany approved these changes
Muy bonito todo

2024-07-01 03:55 UTC, DMarjar approved these changes

2024-07-01 03:55 UTC, merged