Feature/back fix complete mission
DMarjar/project-dudu pull request #75
Opened 2024-08-09 23:31 UTC by CarmonaMedinaMaycon

2024-08-10 01:55 UTC, DMarjar approved these changes

2024-08-10 01:55 UTC, DMarjar commented on modules/missions/complete_mission/app.py
> +                        response = {
incluye en el response si no subio de nivel cuanta experiencia gano para que se pueda mostrar una pequeña alerta

2024-08-10 01:55 UTC, DMarjar commented on modules/missions/complete_mission/app.py
> +                        response = {
incluye en el response si subio de nivel cuanta experiencia gano para que se incluya en la alerta

2024-08-10 01:55 UTC, DMarjar requested changes
cambiar

2024-08-11 23:17 UTC, DaddyDany approved these changes
Donde no jale tu pr

2024-08-11 23:35 UTC, DMarjar approved these changes
mu bien

2024-08-11 23:36 UTC, merged